# Generated by Django 5.0.14 on 2026-04-09 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True)),
                ('city', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=160)),
                ('country', models.CharField(default="O'zbekiston", max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['city', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('category', models.CharField(choices=[('Sedan', 'Sedan'), ('SUV', 'SUV / Crossover'), ('Premium', 'Premium'), ('Minivan', 'Minivan'), ('Elektr', 'Elektr')], max_length=20)),
                ('emoji', models.CharField(default='🚗', max_length=12)),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seats', models.PositiveSmallIntegerField(default=5)),
                ('transmission', models.CharField(default='Avtomat', max_length=40)),
                ('fuel', models.CharField(default='Benzin', max_length=40)),
                ('badge', models.CharField(blank=True, max_length=40)),
                ('description', models.TextField(blank=True)),
                ('photo_url', models.URLField(blank=True)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['price_per_day', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('message', models.TextField()),
                ('is_reviewed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_code', models.CharField(editable=False, max_length=16, unique=True)),
                ('full_name', models.CharField(max_length=140)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=40)),
                ('passport_id', models.CharField(max_length=40)),
                ('flight_number', models.CharField(blank=True, max_length=40)),
                ('arrival_date', models.DateField()),
                ('departure_date', models.DateField()),
                ('days', models.PositiveSmallIntegerField(default=1, editable=False)),
                ('service_fee', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('confirmed', 'Tasdiqlandi'), ('active', 'Jarayonda'), ('completed', 'Tugallandi'), ('cancelled', 'Bekor qilindi')], default='confirmed', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='rental.airport')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='rental.car')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
