REVIEWS = [
    {
        "stars": "5.0 / 5",
        "text": "Toshkentga tungi reys bilan keldim. Avtomobil qabul qilish nuqtasida tayyor edi va rasmiylashtirish uzoq cho'zilmadi.",
        "name": "Jasur Nazarov",
        "country": "Toshkent, O'zbekiston",
        "avatar": "JN",
    },
    {
        "stars": "5.0 / 5",
        "text": "Istanbul safarida bron oldindan tasdiqlandi. Yetib kelganimda qabul qilish jarayoni aniq va tushunarli bo'ldi.",
        "name": "Malika Rahimova",
        "country": "Samarqand",
        "avatar": "MR",
    },
    {
        "stars": "4.8 / 5",
        "text": "Oilaviy safar uchun oldindan bron qildik. Avtomobil holati va qaytarish shartlari buyurtmadagi ma'lumotga mos chiqdi.",
        "name": "Bobur Xoliqov",
        "country": "Andijon",
        "avatar": "BX",
    },
]

AIRPORTS = [
    {"code": "TAS", "city": "Toshkent", "name": "Islom Karimov xalqaro aeroporti", "country": "O'zbekiston"},
    {"code": "SKD", "city": "Samarqand", "name": "Samarqand xalqaro aeroporti", "country": "O'zbekiston"},
    {"code": "BHK", "city": "Buxoro", "name": "Buxoro xalqaro aeroporti", "country": "O'zbekiston"},
    {"code": "AZN", "city": "Andijon", "name": "Andijon aeroporti", "country": "O'zbekiston"},
    {"code": "NMA", "city": "Namangan", "name": "Namangan aeroporti", "country": "O'zbekiston"},
    {"code": "FEG", "city": "Farg'ona", "name": "Farg'ona aeroporti", "country": "O'zbekiston"},
    {"code": "NCU", "city": "Nukus", "name": "Nukus aeroporti", "country": "O'zbekiston"},
    {"code": "IST", "city": "Istanbul", "name": "Istanbul Airport", "country": "Turkiya"},
    {"code": "DXB", "city": "Dubai", "name": "Dubai International", "country": "BAA"},
    {"code": "FRA", "city": "Frankfurt", "name": "Frankfurt Main", "country": "Germaniya"},
]

CARS = [
    {
        "name": "Chevrolet Malibu",
        "slug": "chevrolet-malibu",
        "category": "Sedan",
        "price_per_day": "45.00",
        "seats": 5,
        "transmission": "Avtomat",
        "fuel": "Benzin",
        "description": "Shahar va biznes safarlar uchun sokin sedan. Aeroportdan ofisgacha qulay, bagaji keng.",
        "photo_url": "https://images.unsplash.com/photo-1549924231-f129b911e442?auto=format&fit=crop&w=1400&q=80",
    },
    {
        "name": "Hyundai Tucson",
        "slug": "hyundai-tucson",
        "category": "SUV",
        "price_per_day": "65.00",
        "seats": 5,
        "transmission": "Avtomat",
        "fuel": "Benzin",
        "description": "Oila, yuk va tog' yo'llari uchun universal crossover. Konditsioner va xavfsizlik paketlari bor.",
        "photo_url": "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=1400&q=80",
    },
    {
        "name": "Toyota RAV4",
        "slug": "toyota-rav4",
        "category": "SUV",
        "price_per_day": "75.00",
        "seats": 5,
        "transmission": "Avtomat",
        "fuel": "Benzin",
        "description": "Uzoq marshrutlarda ishonchli, baland klirensli SUV. Aeroportdan turistik yo'nalishlarga tayyor.",
        "photo_url": "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?auto=format&fit=crop&w=1400&q=80",
    },
    {
        "name": "Toyota Camry",
        "slug": "toyota-camry",
        "category": "Premium",
        "price_per_day": "80.00",
        "seats": 5,
        "transmission": "Avtomat",
        "fuel": "Benzin",
        "description": "VIP kutib olish, uchrashuvlar va mehmonlar uchun premium sedan.",
        "photo_url": "https://images.unsplash.com/photo-1553440569-bcc63803a83d?auto=format&fit=crop&w=1400&q=80",
    },
    {
        "name": "Mercedes E-Class",
        "slug": "mercedes-e-class",
        "category": "Premium",
        "price_per_day": "130.00",
        "seats": 5,
        "transmission": "Avtomat",
        "fuel": "Benzin",
        "description": "Biznes klass saloni, yumshoq yurish va sokin interyer. Muhim mehmonlarni kutib olishga mos.",
        "photo_url": "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1400&q=80",
    },
    {
        "name": "Kia Carnival",
        "slug": "kia-carnival",
        "category": "Minivan",
        "price_per_day": "90.00",
        "seats": 8,
        "transmission": "Avtomat",
        "fuel": "Diesel",
        "description": "Katta oila, jamoa yoki ko'p bagaj uchun 8 o'rinli minivan.",
        "photo_url": "https://images.unsplash.com/photo-1541443131876-44b03de101c5?auto=format&fit=crop&w=1400&q=80",
    },
    {
        "name": "BYD Atto 3",
        "slug": "byd-atto-3",
        "category": "Elektr",
        "price_per_day": "55.00",
        "seats": 5,
        "transmission": "Avtomat",
        "fuel": "Elektr",
        "description": "Tejamkor elektr crossover. Shahar bo'ylab sokin va arzon harakatlaning.",
        "photo_url": "https://images.unsplash.com/photo-1619767886558-efdc259cde1a?auto=format&fit=crop&w=1400&q=80",
    },
    {
        "name": "Tesla Model 3",
        "slug": "tesla-model-3",
        "category": "Elektr",
        "price_per_day": "95.00",
        "seats": 5,
        "transmission": "Avtomat",
        "fuel": "Elektr",
        "description": "Elektr premium sedan. Tezlanishi kuchli, saloni minimal, sayohat hissi boshqacha.",
        "photo_url": "https://images.unsplash.com/photo-1560958089-b8a1929cea89?auto=format&fit=crop&w=1400&q=80",
    },
]
